name: project
description: "A new Flutter project."
# La ligne suivante empêche le package d'être publié accidentellement sur pub.dev en utilisant `flutter pub publish`.
# Cela est préférable pour les packages privés.
publish_to: 'none' # Supprimez cette ligne si vous souhaitez publier sur pub.dev

# La section suivante définit la version et le numéro de build de votre application.
# Un numéro de version est composé de trois nombres séparés par des points, comme 1.2.43,
# suivi éventuellement d'un numéro de build séparé par un +.
# La version et le numéro de build peuvent être remplacés lors de la compilation avec flutter
# en spécifiant respectivement --build-name et --build-number.
# Sur Android, build-name est utilisé comme versionName tandis que build-number est utilisé comme versionCode.
# Pour en savoir plus sur le versionnement Android : https://developer.android.com/studio/publish/versioning
# Sur iOS, build-name est utilisé comme CFBundleShortVersionString tandis que build-number est utilisé comme CFBundleVersion.
# Pour en savoir plus sur le versionnement iOS :
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# Sur Windows, build-name est utilisé comme parties majeure, mineure et de correction
# des versions du produit et du fichier, tandis que build-number est utilisé comme suffixe de build.
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

# Les dépendances spécifient les autres packages dont votre package a besoin pour fonctionner.
# Pour mettre automatiquement à jour les dépendances de votre package vers les dernières versions
# envisagez d'exécuter `flutter pub upgrade --major-versions`. Alternativement,
# les dépendances peuvent être mises à jour manuellement en modifiant les numéros de version ci-dessous
# à la dernière version disponible sur pub.dev. Pour voir quelles dépendances ont des versions plus récentes disponibles,
# exécutez `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  cupertino_icons: ^1.0.6
  photo_view: ^0.14.0
  carousel_slider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Le package "flutter_lints" ci-dessous contient un ensemble de lints recommandés pour
  # encourager de bonnes pratiques de codage. L'ensemble de lints fourni par le package est
  # activé dans le fichier `analysis_options.yaml` situé à la racine de votre package.
  # Consultez ce fichier pour des informations sur la désactivation de règles de lint spécifiques
  # et l'activation d'autres règles supplémentaires.
  flutter_lints: ^3.0.0

# Pour des informations sur la partie Dart générique de ce fichier, voir
# la page suivante : https://dart.dev/tools/pub/pubspec

# La section suivante est spécifique aux packages Flutter.
flutter:

  # La ligne suivante garantit que la police Material Icons
  # est incluse dans votre application, afin que vous puissiez utiliser les icônes dans
  # la classe material Icons.
  uses-material-design: true

  # Pour ajouter des ressources à votre application, ajoutez une section assets, comme ceci :
  assets:
    - assets/images/
 
  # Une ressource image peut faire référence à une ou plusieurs "variantes" spécifiques à la résolution, voir
  # https://flutter.dev/assets-and-images/#resolution-aware

  # Pour plus de détails sur l'ajout de ressources à partir de dépendances de packages, voir
  # https://flutter.dev/assets-and-images/#from-packages

  # Pour ajouter des polices personnalisées à votre application, ajoutez une section fonts ici,
  # dans cette section "flutter". Chaque entrée dans cette liste doit avoir une
  # clé "family" avec le nom de la famille de polices, et une clé "fonts" avec un
  # liste donnant la ressource et d'autres descripteurs pour la police. Par exemple :
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # Pour plus de détails sur les polices provenant de dépendances de packages,
  # voir https://flutter.dev/custom-fonts/#
